#   _____        _       _              _ _                 _ _      __  __                                   
#  |  __ \      | |     | |            | ( )          /\   | | |    |  \/  |                                  
#  | |  | |_   _| |_ ___| |__   ___  __| |/ ___      /  \  | | |_   | \  / | __ _ _ __   __ _  __ _  ___ _ __ 
#  | |  | | | | | __/ __| '_ \ / _ \/ _` | / __|    / /\ \ | | __|  | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
#  | |__| | |_| | || (__| | | |  __/ (_| | \__ \   / ____ \| | |_   | |  | | (_| | | | | (_| | (_| |  __/ |   
#  |_____/ \__,_|\__\___|_| |_|\___|\__,_| |___/  /_/    \_\_|\__|  |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|   
#                                                                                              __/ |          
#                                                                                             |___/           

owner:
# Syntax: - 443762652259418132 (Your Discord ID), there can be multiple owners
  - 443762652259418132

startup:
# Manage your start-up
  verify: true # Check if you have setup the bot correctly
  versionCheck: true # Check if you are running the latest version

discord:
# Manage your discord settings
  botToken: "OTU5NDM3MDAxODQzNjgzNDI4.Ykb3Vg.kJYOZd1_UAqTtfWs_wWjG0_LegI" # Don't forget to enable intents (https://youtu.be/pzxVzEHk4ww?t=35)
  prefix: "!"

format:
# Customize your embeds
  successTitle: "Success!"
  errorTitle: "Error!"
  footer: "Dutched's Alt Manager v1.5.1"
  embedColor: "#9702ed"

minecraft:
# Minecraft settings
  auth: "mojang" # Pick either mojang/microsoft
  serverIP: "play.breachpvp.nl"
  serverPort: "25565"
  version: "1.8.9"
  joinCommand: "/yellow"
  joinDelay: 3 # Time in between alts joining (in seconds)
  hideErrors: true # To hide the "unknown transaction" warning, if you have trouble getting the bots up you might want to change this to false

alts:
# This can be an infinite amount of alts, remember to fill it out like this "- AltEmail@email.com:Password123!"
- "dinistb77@gmail.com:Dinistb2005"
- "brandon-jones@live.ca:Phoenix988@"
- "lucas.tranape@gmail.com:Lucas778637"
- "damian_sara_94@hotmail.com:Damian19940@"